[[redirects]]
    from = "/journal/*"
    to = "https://bejewelled-ganache-8d2d14.netlify.app/journal/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/blog/*"
    to = "https://roaring-flan-f9eca9.netlify.app/:splat"
    status = 200
    force = true